### ISSUE TITLE
The difference of this and regular chromium? 

### ISSUE THREAD

**Issue by xu3s** [luanon404/seledroid-drivers#1]
What is the differences of this driver and the regular chromium?
If it was your own build browser can you share the source code?

**Comment by luanon404** [comment]
> What is the differences of this driver and the regular chromium? If it was your own build browser can you share the source code?

sorry for late
1> its my own application build in java language
2> i'm very busy so i will update when i have time

**Comment by xu3s** [comment]
Ok, it's fine. I'm just a little bit uncomfortable installing unknown apps, i apologize.

**Comment by luanon404** [comment]
i will close this issues, if you still have any questions just reopen.
